### ISSUE TITLE
Develop and upload privacy container

### ISSUE THREAD

**Issue by CmCC1435** [chorus-ai/chorus-cloud-pm#10]
@CmCC1435 - once the headless version of the package is committed to the [privacy_scan_tool](https://github.com/chorus-ai/privacy_scan_tool), I will add it to the [ETL container](https://github.com/chorus-ai/chorus-container-apps/tree/main/etl) as a prefect process flow that can be deployed centrally.

@anotherkaizhang - when you update the repo, could you please also create a versioned release of the tool as a formal python package using guidelines specified in [chorus-developer](https://chorus-ai.github.io/chorus-developer/releaseProcess.html#Version_numbering)?

**Comment by jshoughtaling** [comment]
Done!
- Version v1.0.0 applied
- Docker image created (see [`chorus-privacy`](https://github.com/chorus-ai/privacy_scan_tool/pkgs/container/chorus-privacy))
- [Package status](https://chorus-ai.github.io/chorus-developer/packageStatuses.html) page updated
