### ISSUE TITLE
1.2 Provisioning environment for analysis

### ISSUE THREAD

**Issue by CmCC1435** [chorus-ai/chorus-cloud-pm#17]
- DevOps for provisioning environments

- [ ] Establishing the private vs public view for other challenge participants

**Comment by rkamaleswaran** [comment]
The DevOps environment is still in development mode, the basic skeleton is in place, however, many other services are still not incorporated into terraform, e.g. leaderboard, discussions, benchmarking. Needs maturation and development.

-- Initial bolus of work need to be done to do the initial production; containers are based on docker so local developments can be performed before pushed to azure. 
-- Testbed for the app development, validation, and push to Chorus
-- -- Pipeline for build, testing and reference on azure is available, and to be used for chorus applications.  (available in azure advisor, recommendations and notes available _ZZZZZZ_)


@Tony to work with Dileep: terraform for the challenge services (primarily web-based tools and data provisioning)

**Comment by rkamaleswaran** [comment]
Dileep to meet with Jared to discuss the DevOps and scripting needs for the data challenge

Investigate operationalization of the data challenge support tools to monitor utilization, computation, and costs

**Comment by CmCC1435** [comment]
Dev environment is needed first

Production/admin for dataset provisioning space needs to be created
--Jared is meeting with Jon to implement terraform
--Dileep needs access to Gitlab/terraform

**Comment by CmCC1435** [comment]
Go forward with user container apps instead of workspace approach

**Comment by rkamaleswaran** [comment]
@jshoughtaling  can you please update this. Do we have a final config and strategy for the user container apps to implement private workspaces for each participant? 

We need to create a container app for a 'demo challenge team' that has jupyter notebook, and access to the data to run some demo ML tasks.

**Comment by CmCC1435** [comment]
Each user can get a portal (firefox browser) that they can access the jupyter access
