### ISSUE TITLE
7. Discussion board to be created for participants

### ISSUE THREAD

**Issue by CmCC1435** [chorus-ai/chorus-cloud-pm#41]
- Need to develop or link to a discussion board where participants will be able to ask organizers questions and/or share resources among each other.

**Comment by CmCC1435** [comment]
**Using possible Github/Gitlab discussions for posting**
second option: Slack like app alternative that can be run in a container

**Comment by jshoughtaling** [comment]
I've deployed MatterMost in the container app environment. You can access it through your Firefox browser at the following address: https://ca-b2ai-mattermost.internal.politebay-bfb3a8cd.eastus2.azurecontainerapps.io

You will need to sign up on the first access (EntraID integration requires an enterprise license).

![Image](https://github.com/user-attachments/assets/524c77c8-4c5b-434f-bd1b-ff69470dff04)

**Comment by CmCC1435** [comment]
If we can use firefox that might be better used in GITLab

How do we want to use GitLab fully?
